#!/bin/sh

# Modal map the pitch to a particular output mode
#   cpan App::MusicTools
# should install this command. (A particular mapping such as this one
# could be hard-coded into an array or hash lookup, but being able to
# fiddle with it is useful.)
canonical modal --raw \
  --input=1,1,1,1,1,1,1,1 \
 --output=1,2,1,3,1,2,1,4 --nos --sp=0 --ep=0 - \
| ./ints2music
