# Only for use with gen-*.pl scripts herein (mostly due to the otherwise
# naughty use of @EXPORT).

use strict;
use warnings;

package SharedMusic;
require Exporter;
our @ISA    = qw(Exporter);
our @EXPORT = qw(%Num2Note $Measures $Smallest_Note @Durs &increment_beat);

our $Measures = 61;
our %Num2Note = qw/0 e 1 f 2 g 3 aes 4 bes 5 ces/;

our @Durs = (
  [qw/8 8 8 8/], [qw/8 8 4/], [qw/8 4 8/], [qw/4 8 8/], [qw/4 4/], [qw/2/],
  [qw/8 16 16 8 8/], [qw/8 8 8 16 16/],
);
our $Smallest_Note = 16;

sub increment_beat {
  my $duration = shift;
  return 1 / ( $duration / $Smallest_Note );
}

print "% generated by $0\n";

1;
